include $(srctree)/drivers/misc/mediatek/Makefile.custom

ccflags-y += -I$(src)/inc -I$(srctree)/include/linux/camera

obj-y	+= kd_flashlightlist.o
obj-y	+= main_strobe_2ndPart_2.o
obj-y	+= strobe_part_id.o
obj-y	+= sub_strobe_2ndPart_2.o
obj-y	+= sub_strobe.o

