include $(srctree)/drivers/misc/mediatek/Makefile.custom
ccflags-y += -I$(MTK_PATH_PLATFORM)/drivers/i2c -I$(srctree)/arch/arm/mach-$(MTK_PLATFORM)

obj-$(CONFIG_MTK_I2C) := i2c.o i2c_common.o

#objs-m := i2c_ut.o
#obj-m += i2c_pcie.o
#obj-m += i2c_pcie_show.o

