ccflags-y += -I$(srctree)/drivers/misc/mediatek/smi/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/dispsys/$(CONFIG_MTK_PLATFORM)
ccflags-y += -I$(srctree)/drivers/misc/mediatek/camera/$(CONFIG_MTK_PLATFORM)
obj-y += camera_isp.o
obj-y += camera_pipe_mgr.o
obj-y += camera_sysram.o
